import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const cfdi_document_tables: KirletTableDecl[] = [
  {
    name: "cfdi_document",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "status", type: "text" },
      { name: "perfil_emision", type: "text" },
      { name: "receptor_rfc", type: "text" },
      { name: "receptor_nombre", type: "text" },
      { name: "emisor_rfc", type: "text" },
      { name: "emisor_nombre", type: "text" },
      { name: "total", type: "real" },
      { name: "uuid", type: "text" },
      { name: "purchase_order_nombre", type: "text" },
      { name: "purchase_order_id", type: "text" },
      { name: "flow_direction", type: "text" },
      { name: "severity", type: "text" },
      { name: "canonical", type: "json" },
      { name: "validation_issues", type: "json" },
      { name: "source_type", type: "text" },
      { name: "source_id", type: "text" },
      { name: "issuer_profile", type: "text" },
      { name: "contacto", type: "text" },
      { name: "json_revision", type: "real" },
      { name: "purchase_order", type: "text" },
    ],
    indexes: [
      { name: "idx_cfdi_document_name", columns: ["name"] },
      { name: "idx_cfdi_document_active", columns: ["is_active"] },
    ],
  },
];
