import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { cfdi_document_pages } from "./cfdi-document.pages.ts";
import { cfdi_document_tables } from "./cfdi-document.tables.ts";

export const cfdi_document_module = define_module({
  resource: "cfdi-document",
  labels: {
    singular: "Cfdi Document",
    plural: "Cfdi Document",
    read: "Ver Cfdi Document",
    write: "Editar Cfdi Document",
  },
  routes: define_crud({
    resource: "cfdi-document",
    table: "cfdi_document",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "cfdi-doc",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      status: { type: "string", search: true },
      perfil_emision: { type: "string", search: true },
      receptor_rfc: { type: "string", search: true },
      receptor_nombre: { type: "string", search: true },
      emisor_rfc: { type: "string", search: true },
      emisor_nombre: { type: "string", search: true },
      total: { type: "number" },
      uuid: { type: "string", search: true },
      purchase_order_nombre: { type: "string", search: true },
      purchase_order_id: { type: "string", search: true },
      flow_direction: { type: "string", search: true },
      severity: { type: "string", search: true },
      canonical: { type: "json" },
      validation_issues: { type: "json" },
      source_type: { type: "string", search: true },
      source_id: { type: "string", search: true },
      issuer_profile: { type: "string", search: true },
      contacto: { type: "string", search: true },
      json_revision: { type: "number" },
      purchase_order: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: cfdi_document_tables,
  pages: cfdi_document_pages,
  menu: [],
});
